version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - '8080:8080'
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=test_user
        - POSTGRES_PASSWORD=password
      ports:
        - '5432:5432'
      volumes:
        - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local